apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wine-train-e7365780755f1873f81392f13d4493d910b3333f
  namespace: default
spec:
  workflowTemplateRef:
    name: wine-train-template
  arguments:
    parameters:
      - name: image
        value: ghcr.io/pekk4/mltest-model:e7365780755f1873f81392f13d4493d910b3333f
      - name: tracking_uri
        value: http://mlflow.mlflow.svc.cluster.local
      - name: s3_endpoint
        value: http://minio.minio.svc.cluster.local:9000
