apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: wine-train-template
  namespace: argo
spec:
  entrypoint: train
  arguments:
    parameters:
      - name: image
      - name: tracking_uri
      - name: s3_endpoint
  serviceAccountName: argo-workflow

  templates:
    - name: train
      container:
        image: "{{workflow.parameters.image}}"
        command: ["python"]
        args: ["train.py"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.tracking_uri}}"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "{{workflow.parameters.s3_endpoint}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: accesskey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: secretkey
