apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wine-train-7fe1385d0ec18d29a2ec2cf64e2f6779bc0a6f68
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  workflowTemplateRef:
    name: wine-train-template
  arguments:
    parameters:
      - name: image
        value: ghcr.io/pekk4/mltest-model:7fe1385d0ec18d29a2ec2cf64e2f6779bc0a6f68
      - name: tracking_uri
        value: http://mlflow.mlflow.svc.cluster.local
      - name: s3_endpoint
        value: http://minio.minio.svc.cluster.local:9000
