apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wine-train-17b57b042ccb922e495b65cad82cb3543f988b3b
  namespace: argo
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  workflowTemplateRef:
    name: wine-train-template
  arguments:
    parameters:
      - name: image
        value: ghcr.io/pekk4/mltest-model:17b57b042ccb922e495b65cad82cb3543f988b3b
      - name: tracking_uri
        value: http://mlflow.mlflow.svc.cluster.local
      - name: s3_endpoint
        value: http://minio.minio.svc.cluster.local:9000
