apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "wine"
  annotations:
    # Keep these as they help construct the URL
    serving.kserve.io/s3-endpoint: minio.minio.svc.cluster.local:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: us-east-1
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/0/models/m-2c9bf5a312524e889f9ab013e80ec303/artifacts"
